### ISSUE TITLE
소스 통일성을 위한 작업

### ISSUE THREAD

**Issue by changwookjun** [NLP-kr/tensorflow-ml-nlp-tf2#1]
아래 사항 통일성 위해 넣을지 뺄지 의견 수렴 필요 합니다. 
if tf.test.is_gpu_available():
    os.environ["CUDA_VISIBLE_DEVICES"]="0"

**Comment by Taekyoon** [comment]
일반적인 컴퓨터 환경의 경우에는 gpu가 1개만 활용할 것 같아 빼는게 나아보이긴 합니다.
