### ISSUE TITLE
ch6 챗봇만들기

### ISSUE THREAD

**Issue by EndewSeoho** [NLP-kr/tensorflow-ml-nlp-tf2#10]
챗봇만들기 코드를 따라하면서 한가지 든 궁금점인데요
가중치를 저장하고나서 다른 주피터노트북에서 가중치를 갖고오고 싶은데
책에서의
model.load_weights(os.path.join(DATA_OUT_PATH, model_name, SAVE_FILE_NM))
위 코드를 사용하면 
no model found in config file이라는 오류를 접하게 되고
모델 아키텍쳐를 따로 저장해야할 것 같아서
from keras.models import model_from_json

json_string = model.to_json()
위 코드를 사용하면 따로 에러코드 없이 에러가 발생합니다.
혹시 방법이 있으면 알려주실수 있을까요?
따로 코드를 첨부하지않은 이유는 모델 학습 후 바로 사용하는데에는 전혀 문제가 없었기 때문에 첨부하지 않았습니다.

**Comment by Taekyoon** [comment]
안녕하세요. 

먼저 확인해주실 부분이 2가지가 있습니다.

1. `from keras.models import model_from_json` 이라 되어있는데 텐서플로우 2로 실행하시는 것인지 아니면 케라스로 실행하는 것인지 확인 바랍니다.
2. 저희 실습한 파일 내용에 대한 환경과 동일하게 구성이 되어있는지 확인해주세요.

추가로 실행하신 코드 내용에 어느 에러가 어떻게 나는지 확인이 어렵습니다. 해결을 위해서는 실습 코드와 에러 메세지도 같이 남겨주시면 감사하겠습니다.

**Comment by Taekyoon** [comment]
더 이상 진행하는 내용이 없어 close 합니다.
