### ISSUE TITLE
2장에 2.2.sklearn.ipynb 파일에 TfidfVectorizer 코드 오류

### ISSUE THREAD

**Issue by monetd** [NLP-kr/tensorflow-ml-nlp-tf2#17]
코드 실행에 오류가 있는건 아니지만 해당 노트북에 TfidfVectorizer 설명 부분에

```python
sentence = [text_data[3]] # ['점심 먹고 공부 해야지']
print(tfidf_vectorizer.transform(text_data).toarray())
```

이 부분의 print문의 text_data가 sentence로 바뀌어야 할 것 같네요 :-)

```python
sentence = [text_data[3]] # ['점심 먹고 공부 해야지']
# text_data를  sentence로 수정
print(tfidf_vectorizer.transform(sentence).toarray())
```

**Comment by Taekyoon** [comment]
안녕하세요.

말씀하신 내용 확인을 하니 해당 부분에 오타가 있는 것을 확인했습니다.
책 내용에는 말씀하신대로 `sentence`로 되어있어 코드 수정만 하면 될 것 같습니다.
코드 오타 확인해주시고 알려주셔서 감사합니다 :)

**Comment by Taekyoon** [comment]
수정 반영했습니다.

이슈 close 합니다.
