### ISSUE TITLE
2장 27페이지 합성곱 신경망 ValueError

### ISSUE THREAD

**Issue by ParkIlseop** [NLP-kr/tensorflow-ml-nlp-tf2#18]
### 실습 환경
- macOS BigSur 11.2
- conda 가상 환경 
- python version 3.6.12
- tensorflow version 2.2.0
- jupyter version 1.0.0
- 기타 : 1장 14페이지에 기재된 requirement 라이브러리 항목 모두 설치

### code 
- 27페이지 Conv1D

```javascript
import tensorflow as tf 
INPUT_SIZE=(1, 28, 28)

inputs = tf.keras.Input(shape=INPUT_SIZE)
conv=tf.keras.layers.Conv1D(
        filters=10,
        kernel_size=3,
        padding='same',
        activation=tf.nn.relu)(inputs)
```

### error massage

ValueError: Input 0 of layer conv1d is incompatible with the layer: expected ndim=3, found ndim=4. Full shape received: [None, 1, 28, 28]

### etc.
- 코랩에서 동일한 코드 실행하면 오류 없음.
- tensorflow version 2.4.0-rc0 버전에서 실행하면 오류 없음.

**Comment by reniew** [comment]
넵 동일환경에서 이슈 발생하는것 확인했습니다.
환경따라 조금 다른 부분이 있는듯해 좀 더 확인해본 후 답변드리도록 하겠습니다!

**Comment by reniew** [comment]
tensorflow 2.2.0 버전에서 발생하는 에러로, 해당 예제를 실행할때만 문제가 되고 2.2.0 버전으로 이후 예제들의 경우에는 정상적으로 사용가능합니다.
앞부분 모듈 설명 부분에서만 colab을 통해 tensroflow>=2.3.0 버전을 사용하시는 것을 추천드립니다.
