### ISSUE TITLE
Docker gpu image 빌드 중 오류

### ISSUE THREAD

**Issue by InchangPark** [NLP-kr/tensorflow-ml-nlp-tf2#19]
Docker GPU image  빌드중 아래와 같은 오류가 발생합니다. 

Reading package lists...
E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release' no longer has a Release file.
E: The repository 'https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release' no longer has a Release file.

**Comment by Taekyoon** [comment]
안녕하세요.
먼저 어떤 환경에서 어떻게 Docker GPU image를 빌드하셨는지 알 수 있을까요?

**Comment by InchangPark** [comment]
안녕하세요.
Linux OS  버전, docker 버전, 실행  command는 아래와 같습니다.

Linux version 4.15.0-135-generic (buildd@lgw01-amd64-005) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #139-Ubuntu SMP Mon Jan 18 17:38:24 UTC 2021

Python 3.8.6

Docker version 20.10.3, build 48d30b5

(law) @data-desktop:~/nlpbook/tensorflow-ml-nlp-tf2$ ./build_jupyter_for_gpu.sh
Sending build context to Docker daemon    521MB
Step 1/20 : FROM tensorflow/tensorflow:2.2.0-gpu
 ---> f5ba7a196d56
Step 2/20 : MAINTAINER taekyoon <tgchoi03@gmail.com>
 ---> Using cache
 ---> 6421d904bb4e
Step 3/20 : RUN apt-get update -y && apt-get install -y wget unzip language-pack-ko openjdk-8-jdk curl git-core locales
 ---> Running in 8d9c345c2c0b
Ign:1 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:4 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Ign:5 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Get:6 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1386 kB]
Err:7 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release
  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 152.199.39.144 443]
Get:8 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Err:9 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release
  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 152.199.39.144 443]
Get:10 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [2157 kB]
Get:11 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [293 kB]
Get:12 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [1921 kB]
Get:13 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [2352 kB]
Get:14 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [35.5 kB]
Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [42.6 kB]
Get:16 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [323 kB]
Get:17 http://archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages [11.3 kB]
Get:18 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [11.4 kB]
Reading package lists...
E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release' no longer has a Release file.
E: The repository 'https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release' no longer has a Release file.
The command '/bin/bash -c apt-get update -y && apt-get install -y wget unzip language-pack-ko openjdk-8-jdk curl git-core locales' returned a non-zero code: 100

**Comment by Taekyoon** [comment]
말씀하신 부분에 이슈가 있을까 하여 제가 가지고 있는 mac 환경에서 동작을 했을 때는 큰 문제는 없는 것으로 확인이 되었습니다.
아마도 지금 발생하신 문제는 패키지에 대한 proxy 연결에 문제가 있을 것으로 보고 있습니다.
제가 인창님의 환경과 동일하지 않아 완전히 해결할 수 있을지는 모르겠습니다만 해결책을 찾게 되면 답변을 남겨드리도록 하겠습니다.

책을 보시고 실습을 하는 상황이실텐데 바로 해결을 해드리지 못해서 죄송합니다.

**Comment by Taekyoon** [comment]
로그를 다시 살피다보니 여기가 문제인 것 같아보입니다.

Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown. Could not handshake: Error in the certificate verification. 

이 이슈에 대해서는 ca-certificate 설치 또는 업데이트가 필요해보입니다. 아래 참고내용을 같이 확인해주시고 이상있을 시 말씀주세요.

https://askubuntu.com/questions/1229122/ubuntu-18-04-apt-update-failed-for-https-repository
