### ISSUE TITLE
Chapter 4 학습 이후 Eval + 캐글 재출용 로직 확인

### ISSUE THREAD

**Issue by rainmaker712** [NLP-kr/tensorflow-ml-nlp-tf2#2]
2.0버젼으로 학습까지는 정상적으로 되는 것을 확인

모델을 불러 Eval 데이터에 저장 할 때, 에러가 떠서 확인 필요.

@Taekyoon , @reniew

**Comment by Taekyoon** [comment]
4.1.5에 대해서 최종 평가 데이터 생성 및 캐글 점수 확인까지 검증 완료 했습니다.
구체적인 구현내용과 결과는 아래 링크를 참고하시면 됩니다.

https://github.com/NLP-kr/tensorflow-ml-nlp-tf2/blob/master/4.TEXT_CLASSIFICATION/4.1.6%20RNN%20Classification_tf2.ipynb

첫 시작 코드를 잘 짜주신 덕에 검증을 빠르게 할 수 있었습니다.
감사합니다.
