### ISSUE TITLE
05_텍스트 유사도 전처리 부분

### ISSUE THREAD

**Issue by Ychanho** [NLP-kr/tensorflow-ml-nlp-tf2#20]
책 253p의 중반에 '평가 데이터도 마찬가지로 전체 문장의 길이를 11로 맞춰서 전처리를 마무리했다.' 라고 돼 있는데
문장 길이 전처리는 11이 아니라 31이 아닌가요? 학습 데이터와 평가 데이터 모두 같은 문장길이 제한으로 두는 것으로 알고 있습니다. 

깃허브에 올리신 코드를 보면 그 쪽에서도 31이라고 돼 있기도 하구요 
In [40] 부분 입니다.

**Comment by Taekyoon** [comment]
안녕하세요.
말씀하신 내용을 살펴보니 해당 페이지에 내용에 문장길이 전처리는 11에서 31로 변경되야하는 것을 확인했습니다.
이 내용은 정오표에 반영하도록 하겠습니다. 
감사합니다.

**Comment by Ychanho** [comment]
정오표는 어디서 확인할 수 있을까요?

**Comment by Taekyoon** [comment]
해당 페이지에 '정오표' 탭을 확인해주시면 됩니다.

https://wikibook.co.kr/nlp-tf2/

현재 내용은 정오표에 업데이트 요청이 되어있어 추후에 갱신될 것으로 보입니다.

**Comment by Ychanho** [comment]
감사합니다
