### ISSUE TITLE
Git에 변경된 사항 책 정오표에도 갱신 해주시면 감사하겠습니다.

### ISSUE THREAD

**Issue by seohyunjun** [NLP-kr/tensorflow-ml-nlp-tf2#21]
if tokenize_as_morph:  # 형태소에 따른 토크나이져 처리
                question = prepro_like_morphlized(question)
                answer = prepro_like_morphlized(answer)

299p에  함수내에 tokenize_as_morph에 대한 사용이 없다가 그다음장에 갑자기 나오고,, 

책 정오표 이외에 대한 오류도 많은 거 같습니다.

**Comment by Taekyoon** [comment]
안녕하세요.
말씀하신 부분을 확인하니 6장에 Seq2Seq과 Transformer 모델 전처리 방식이 다르다는 점을 이야기 해주신 듯 합니다.
~~tokenize_as_morph에 관한 설명은 304페이지에 processing 관련 설명에서 언급이 되는 것으로 알고 있는데 ~~
~~구체적으로 어떤 문제가 있는지 설명해주시면 정오표에 업데이트를 할 수 있을 것 같습니다. :)~~

말씀하신 부분에 대해서 이해했습니다. 299 페이지 코드라인에서 부터 tokenize_as_morph 기능에 대한 코드 내용이 누락되어있는 점 확인해서 해당 내용 정오표에 업데이트 할 예정입니다.
좋은 피드백 주셔서 감사합니다! :)
