### ISSUE TITLE
quora-question-pairs-( xg-boost 기법에 TF-IDF 적용방식에 대해서)

### ISSUE THREAD

**Issue by Ychanho** [NLP-kr/tensorflow-ml-nlp-tf2#23]
챕터 5의 텍스트 유사도에 관한 이슈입니다.
xg-boost 방식의 성능을 올리기 위해서 입력값 데이터를 TF-IDF 를 적용해서 다시 해봤습니다. 그런데 해당 캐글 데이터에 nan 데이터가 있었는지 TF-IDF 방식을 거치려고 하면 진행이 되질 않더군요.  그래서 해당 nan 데이터를 찾아 삭제 하고 학습을 거쳤습니다. 그런데 nan 데이터를 지웠어서 캐글 제출 데이터 형식에 맞지를 않습니다. 제가 과정을 잘못 진행한 것일까요 실제로 데이터에 문제가 있는게 맞을까요.
https://github.com/Ychanho/Machine-Learning-Deep-Learning.../tree/main/quora-question-pairs
링크는 제가 학습을 진행한 코드 입니다. nan 데이터 때문에 진행이 안 됐을 때 데이터를 처리하는 부분은 주석처리로 바꿔져 있습니다. 제가 접근을 잘못 한 것이 있다면 가르쳐주시면 감사하겠습니다.

링크에 올려진 대로 학습을 진행하면 오류가 뜨고 주석 처리된 nan데이터 제거 부분 주석처리 없애고 학습시키면 학습이 됩니다.

**Comment by changwookjun** [comment]
NAN이이 왜 발생하는지는 모르겠지만 train_q1_data/train_q2_data 의 크기는 똑같을거 같습니다.
NAN 을 특정 값으로 다 채워주는것은 어떠한가요?

pandas의 fillna 함수를 활용해 보세요 .

**Comment by Ychanho** [comment]
네 fillna 함수를 쓰니 기능 하네요. 왜 nan이 떴는지는 모르겠지만요 ㅎㅎ... 감사합니다
