### ISSUE TITLE
[7장 사전 학습 모델] Naver NLP Challenge  데이터를 구해야하는데 어디서 구하는지 모르겠습니다.

### ISSUE THREAD

**Issue by seohyunjun** [NLP-kr/tensorflow-ml-nlp-tf2#24]
git을 통해 nlp-challenge data를 구했는데 해당 폴더안에는 train_data 밖에 없습니다. 

책 페이지는 402p 입니다.

**Comment by rainmaker712** [comment]
안녕하세요? 해당 데이터는 원본 Path이며,

train/test가 나뉘어진 데이터는 아래 링크를 참조하시면 됩니다.
https://github.com/monologg/korean-ner-pytorch/tree/master/data

공개된 데이터는 train만 존재하여, train 데이터를 나누었습니다.

**Comment by seohyunjun** [comment]
빠른 답변 감사합니다!~ 파일 올려주셔서 감사합니다.
