### ISSUE TITLE
NameError: name 'DATA_IN_PATH' is not defined

### ISSUE THREAD

**Issue by wavgado** [NLP-kr/tensorflow-ml-nlp-tf2#28]
![image](https://user-images.githubusercontent.com/81840499/130169252-e89b4f13-876b-4675-9bf4-870f6c0a3f8c.png)

**Comment by changwookjun** [comment]
안녕하세요. 질문 주셔서 감사합니다. 

혹시 해당 소스는 어디에 위치 할까요 ?

답변 주시면 감사하겠습니다.
