### ISSUE TITLE
it takes too long time installing requirements.

### ISSUE THREAD

**Issue by YeonbiJung** [NLP-kr/tensorflow-ml-nlp-tf2#32]
pip install -r requirements.txt를 통해 필요한 파일을 받고 있습니다.
텍스트 파일에 나온 건 다 설치 한 것 같은데 이외의 다른 .whl 확장자 파일들을 이틀 정도 다운 중인데 정상적인 현상인지 여쭤보고 싶습니다.

**Comment by Taekyoon** [comment]
@YeonbiJung 
혹시 설치하신 아나콘다 또는 미니콘다 버전이 어떻게 되나요?
그리고 실행하신 환경이 어디인지도 궁금합니다.

**Comment by YeonbiJung** [comment]
(base) C:\Users\Brain>anaconda -V
anaconda Command line client (version 1.9.0)
Anaconda Prompt에서 실행했습니다.

**Comment by Taekyoon** [comment]
https://repo.anaconda.com/archive 에 가셔서
`Anaconda3-5.3.0-Windows-x86_64.exe` 버전으로 설치하고 실행해보실 수 있을까요?
구매하신 책이 있으시다면 처음 단원에 가이드를 따라해주시면 좋을 것 같습니다.

**Comment by YeonbiJung** [comment]
설치는 된것 같은데 이후 2-1 ipynb파일을 주피터노트북으로 실행했을 때 tensorflow를 import하려 하는데 모듈이 없다고 합니다.
설치 이후 환경 구성을 어떻게 해야 하나요?

**Comment by Taekyoon** [comment]
pip install이 아직 되지 않으신듯 합니다.
아나콘다 설치를 하신 이후 상황이라면 `requirements.txt`를 `pip -r requirements.txt`로 설치해주시면 됩니다.

**Comment by YeonbiJung** [comment]
해결됐습니다 감사합니다!
