### ISSUE TITLE
02_자연어 처리 개발 준비 - 더미 데이터를 활용한 감정 분석 모델링

### ISSUE THREAD

**Issue by songinno** [NLP-kr/tensorflow-ml-nlp-tf2#34]
- 데이터는 이전 장에서 사용했던 텍스트 데이터를 ~~
- 앞에서 다룬 내용이므로 전처리 과정에 대한 설명은 생략한다.

등의 내용이 있는데, 이 책을 읽기 전, 선행해야 할 도서가 있는건가요?

**Comment by Taekyoon** [comment]
@songinno 안녕하세요. 말씀하신 표현은 책 안에 이전 장에서 설명하거나 보인내용을 가리킨 듯 합니다. 
조금 더 구체적으로 상황을 설명해주시면 자세한 답변을 드릴 수 있을것 같습니다.

cc: @changwookjun

**Comment by songinno** [comment]
자연어처리 입문을 [텐서플로2와 머신러닝으로 시작하는 자연어 처리 로지스틱 회귀부터 BERT와 GTP3까지 (개정 2판)]
해당 도서를 통해 처음 학습중인데,

위에서 말씀드렸던 내용과 같이, 

2장 내용중,
* 데이터는 이전 장에서 사용했던 "텍스트 데이터"를 그대로 사용하고, ....
* 앞에서 다룬 내용이므로 "전처리 과정"에 대한 설명은 생략한다.
등과 같은 문구가 있습니다.

그런데,
1장(들어가며)에서는 "텍스트 데이터"나 "전처리 과정"에 대한 설명은 없었어서,
(1장에서는 본 적 없는 데이터이고, 전처리 과정에 대해 따로 다룬 내용이 없는것같습니다..ㅠ)

그래서 혹시 이 책을 읽기 전에 선행 학습되어야 할 도서가 따로 있는지 문의드립니다.

------------------------------------------------------------------------------------------
"텍스트 데이터"

samples = ['너 오늘 이뻐 보인다',
          '나는 오늘 기분이 더러워',
          '끝내주는데, 좋은 일이 있나봐',
          '나 좋은 일이 생겼어',
          '아 오늘 진짜 짜증나',
          '환상적인데, 정말 좋은거 같아']

**Comment by Taekyoon** [comment]
먼저 확인해보니 책 내용 설명이 잘못되었습니다. 중요한 이슈 제보해주셔서 감사합니다!
저희 책을 보시기전에 먼저 선행해야할 도서는 없습니다. (텐서플로2를 처음 보시는 분들께 가이드하는 책이라서요.)
혹시 해당 내용에서 이해가 가지 않는 내용을 말씀 주시면 아래 이슈 커멘트에 설명드리겠습니다.

제보주신 내용은 책 정오표에 등록하도록 하겠습니다. 
감사합니다!

cc: @changwookjun @rainmaker712 @reniew

**Comment by Taekyoon** [comment]
@songinno 님
저희가 살펴보니 말씀하신 내용은 이미 정오표에 기재되어있어서 링크 공유드립니다.

- 링크: https://wikibook.co.kr/nlprev2/

혹시 다른 궁금한 점이 있으시면 새로운 이슈로 질문 주시면 좋을 것 같습니다.
해당 이슈는 해결된 것으로 보이므로 close 처리 하겠습니다.

**Comment by songinno** [comment]
답변 감사합니다!
