### ISSUE TITLE
dropbox 파일 다운로드가 되지 않습니다.

### ISSUE THREAD

**Issue by RogerHeederer** [NLP-kr/tensorflow-ml-nlp-tf2#4]
https://www.dropbox.com/s/nzfa9xpzm4edp6o/gpt_ckpt.zip

만료가 된 걸까요?

**Comment by Taekyoon** [comment]
안녕하세요. 

오늘 확인해본 결과 dropbox 링크가 만료가 된 것으로 확인되었습니다.
현재는 조취를 취해두어 사용하신 링크로 모델 다운로드가 가능합니다.
추가로 dropbox 링크가 만료되는 이슈가 있어 별도로 모델을 받을 수 있도록 링크를 만들어 두었습니다.

```
!wget https://github.com/NLP-kr/tensorflow-ml-nlp-tf2/releases/download/v1.0/gpt_ckpt.zip -O gpt_ckpt.zip 
```

다음 방식으로도 모델 다운로드가 가능하니 참고 바랍니다.

**Comment by RogerHeederer** [comment]
네 답변 감사합니다!
