### ISSUE TITLE
오타

### ISSUE THREAD

**Issue by Spruce-tone** [NLP-kr/tensorflow-ml-nlp-tf2#5]
100 page 
`from bs4 import Beautiful Soup` > `from bs4 import BeautifulSoup`
로 모듈 import할 때 BeutifulSoup에 띄어쓰기가 되어 있어 에러가 납니다.
이 이후로 BeautifulSoup를 import할 때 모두 띄어쓰기가 있습니다.

173 page
`testDataVecs = vectorizer.transform(test['review'])` > `testDataVecs = vectorizer.transform(test_data['review'])` 
test가 test_data로 수정되어야 할 것 같습니다.

**Comment by Taekyoon** [comment]
안녕하세요.

말씀하신 부분에 대해서 정오표에 추가해 두었습니다.
관심있게 읽어주셔서 감사합니다!

**Comment by Spruce-tone** [comment]
네, 책 재미있게 읽고 공부하고 있습니다
이런책이 많이 있으면 좋겠네요!
