### ISSUE TITLE
Ch4 텍스트 분류 오타

### ISSUE THREAD

**Issue by Spruce-tone** [NLP-kr/tensorflow-ml-nlp-tf2#6]
P179
`test_data_vecs = get_dataset(sentences, model, num_features` 가
`train_data_vecs = get_dataset(sentences, model, num_features` 이 되어야 하는게 아닌지 조심스럽게 추측해 봅니다.

P181

```
for review in test_data: 
    test_sentences.append(review.split())
```

부분이

```
for review in test_review:    
    test_sentences.append(review.split())
```
가 되어야 할것 같습니다.

**Comment by Taekyoon** [comment]
안녕하세요.

저희 책을 관심있게 읽어주셔서 감사합니다.
말씀하신 페이지와 실습코드를 비교해봤습니다. 
책 내용 안에 코드가 오타인 것을 확인했고 해당 내용 정오표에 업데이트 할 예정입니다.

감사합니다!
