### ISSUE TITLE
Ch7 gpt2 문장생성

### ISSUE THREAD

**Issue by Psystar99** [NLP-kr/tensorflow-ml-nlp-tf2#7]
안녕하세요! gpt2를 사용하여 문장을 생성하는 듀토리얼(https://github.com/NLP-kr/tensorflow-ml-nlp-tf2/blob/master/7.PRETRAIN_METHOD/7.4.1.gpt2_finetune_LM.ipynb)을 똑같이 따라하고 있는데요
### **<학습전>**
![스크린샷 2020-11-03 오후 3 25 17](https://user-images.githubusercontent.com/40908279/97955119-c9314680-1de8-11eb-9a57-066176cf60b8.png)
이번에 리드미에 올라온 것과 같이 gpt2 모델 다운로드도 변경하여 문장생성을 진행하였는데 greedy 방식으로는 제대로된 문장이 생성되지 않습니다.

### **<학습후>**
![스크린샷 2020-11-03 오후 3 19 32](https://user-images.githubusercontent.com/40908279/97954849-faf5dd80-1de7-11eb-914e-c990ed76a19a.png)
위와 같이 깃헙에서 올리신 운수좋은 날 소설을 다운 받아 똑같은 방식으로 학습을 진행하였는데요 학습 진행후, greedy는 더욱 안되며 샘플링 방식 또한 제대로된 문장이 생성되지 않아 이슈란에 올려 봅니다. 코드는 깃허브에 있는 코드 그대로 진행했습니다
![스크린샷 2020-11-03 오후 3 28 56](https://user-images.githubusercontent.com/40908279/97955332-4e1c6000-1de9-11eb-89d0-4989e4f8eec8.png)

**Comment by Taekyoon** [comment]
안녕하세요.

우선 저희 책 실습을 활용하면서 좋은 피드백을 주셔서 감사합니다.

제가 위에 이슈 내용을 살펴보면서 여쭤볼게 있는데요. 혹시 환경설정을 하실때 사용하시는 라이브러리중에 glueonnlp와 mxnet, sentencepiece버전이 어떻게 되는지 알 수 있을까요? 저희 'requirements.txt'에 나온 라이브러리 버전과 동일한지도 확인해주시면 감사하겠습니다.

**Comment by Psystar99** [comment]
gluonnlp == 0.9.1
mxnet == 1.6.0
sentencepiece >= 0.1.85
torch == 1.6.0
transformers == 2.11.0
tqdm
tensorboardX
dropbox

와 같이 설정하고 파이썬 버전은 3.6.9입니다. SKT의 koGPT2를 기반으로 프로젝트를 진행하고 있어, 환경설정 부분은 SKT의 requirementx.txt와 실행구문을 참고하여 진행하였습니다:)

**Comment by Taekyoon** [comment]
혹시 프로젝트에 있는 requirements.txt를 따라 환경 구성을 해보실 수 있을까요?
위에 보여주신 환경과 차이는 sentencepiece >= 0.1.85가 sentencepiece == 0.1.85 이렇게 되어있는 겁니다.

만약 이렇게 실행해보시고 문제가 있으시다면 실습 코드에 이와같이 수정을 해주시면 되겠습니다.

```python
tokenizer = SentencepieceTokenizer(TOKENIZER_PATH, num_best=0, alpha=0)
```
진행해보시고 잘되는지 알려주세요 :)
환경 구성을 먼저 해보시고 뒤에 코드 수정을 해주시면 저희 책 개선에도 큰 도움이 될 것 같습니다.

**Comment by Psystar99** [comment]
<img width="1045" alt="스크린샷 2020-11-05 오후 5 02 07" src="https://user-images.githubusercontent.com/40908279/98213593-a5a50200-1f88-11eb-9322-52c621c9518d.png">


<img width="670" alt="스크린샷 2020-11-05 오후 5 02 47" src="https://user-images.githubusercontent.com/40908279/98213654-bc4b5900-1f88-11eb-8d60-6adcc05e177e.png">

감사합니다! 이제 생성이 잘되네요!!!!!

**Comment by Taekyoon** [comment]
감사합니다! 그리고 한가지만 여쭐게요. 

혹시 환경 구성만 바꾼뒤에 정상적으로 나오셨나요?
아니면 소스변경까지 한 후에 정상적으로 나오셨나요?

**Comment by Psystar99** [comment]
위는 환경설정과 소스코드 둘 다 변경하고 돌린 것이었는데 각각의 경우에 대해서 돌려보니 둘 다 잘됩니다!

**-환경설정 변경했을 때:**
<img width="643" alt="스크린샷 2020-11-05 오후 5 27 28" src="https://user-images.githubusercontent.com/40908279/98216278-2f0a0380-1f8c-11eb-96e6-ce33b84955d2.png">
<img width="570" alt="스크린샷 2020-11-05 오후 5 27 41" src="https://user-images.githubusercontent.com/40908279/98216295-36c9a800-1f8c-11eb-9dec-13b4b1952f98.png">

**-소스코드 변경했을 때:**
<img width="749" alt="스크린샷 2020-11-05 오후 5 28 14" src="https://user-images.githubusercontent.com/40908279/98216352-4ba63b80-1f8c-11eb-926b-fb2e9f71248b.png">
<img width="763" alt="스크린샷 2020-11-05 오후 5 28 27" src="https://user-images.githubusercontent.com/40908279/98216369-5234b300-1f8c-11eb-8c3c-73772920ea1e.png">

**Comment by Taekyoon** [comment]
네 제가 한 경험으로는 환경설정 만으로도 가능할듯 싶습니다.
아마 sentencepiece 라이브러리쪽에 토크나이저 기본설정값이 버전이 바뀌면서 달라진 이슈일겁니다.

이 이슈는 해결이 되었으므로 close 하겠습니다.

**Comment by Psystar99** [comment]
네! 감사합니다 :D
