### ISSUE TITLE
chat6 챗봇 seq2seq 모델 학습할때 에러

### ISSUE THREAD

**Issue by KwonMinho** [NLP-kr/tensorflow-ml-nlp-tf2#8]
chat6 챗봇 seq2seq 파트에서 실습을 따라하는 도중에(model.fit)
아래 그림과 같은 Invalid argument..오류가 발생합니다.

index_inputs, index_outputs, index_targets 모두 shape해서 출력해보고 len해서 출력해봤는데 서로 같은 모양을 가지고 있습니다.

대체 무엇이 문제인지 몰라서... 질문 드립니다.
![211](https://user-images.githubusercontent.com/36630283/98776660-bcd56b00-2432-11eb-81f6-957440d91753.png)

**Comment by Taekyoon** [comment]
안녕하세요.

에러 문제에 대해서 여쭤보기에 앞서 모델 학습에서 사용하신 환경을 알려주실 수 있을까요?
그리고 사용하신 환경이 저희 책 실습에서 사용하는 환경과 동일한지도 확인해주시면 감사하겠습니다.

**Comment by KwonMinho** [comment]
다시 삭제하고  설치하니깐 잘 동작합니다. 감사합니다.
